---
- name: Update web servers
  hosts: web
  remote_user: root
  become: true

  tasks:
  - name: install git & java
    yum:
      name:
        - git
        - java-1.8*

  - name: download tom
    ansible.builtin.command: wget http://archive.apache.org/dist/tomcat/tomcat-8/v8.0.23/bin/apache-tomcat-8.0.23.tar.gz
    become: yes
    args:
      chdir: /opt/

  - name: untaring tomcat
    ansible.builtin.unarchive:
      src: /opt/apache-tomcat-8.0.23.tar.gz
      dest: /opt/
      remote_src: yes

  - name: clone repo
    ansible.builtin.git:
      repo: https://github.com/hemanthkuncha/javaprojects.git
      dest: /opt/artifacts

  - name: copy artifacts to tomcat
    ansible.builtin.copy:
      src: /opt/artifacts/target/local-war-linix.war
      dest: /opt/apache-tomcat-8.0.23/webapps/
      remote_src: yes
      follow: no


  - name: copy tomcat conf file
    ansible.builtin.copy:
      src: /opt/artifacts/tomcat-users.xml
      dest: /opt/apache-tomcat-8.0.23/conf/
      follow: no
      remote_src: yes

  - name: start tomcat
    ansible.builtin.shell:
      cmd: ./startup.sh
      chdir: /opt/apache-tomcat-8.0.23/bin/
