AWSTemplateFormatVersion: "2010-09-09"
Description: docker stack.
Resources:
  ansibleserver:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0427090fd1714168b
      InstanceType: t2.micro
      KeyName: laptop
      Tags:
        -
          Key: Name
          Value: Docker-server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum install docker
          yum install git
          chmod 666 /run/docker.sock
          systemctl start docker
          systemctl enable docker
