AWSTemplateFormatVersion: "2010-09-09"
Description: docker stack.
Resources:
  ansibleserver:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0427090fd1714168b
      InstanceType: t2.micro
      KeyName: laptop
      Tags:
        -
          Key: Name
          Value: Docker-server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo dnf install docker -y
          sudo dnf install git -y
          sudo systemctl start docker
          sudo chmod a=rw /run/docker.sock
          sudo systemctl enable docker
