AWSTemplateFormatVersion: "2010-09-09"
Description: Jenkins-Server practice stack.
Resources:
  tomcatserver:
    Type: 'AWS::EC2::Instance'
    Properties: 
      ImageId: ami-0427090fd1714168b
      InstanceType: t2.micro
      KeyName: desktop
      Tags:
        -
          Key: Name
          Value: Jenkins-Server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo yum update –y
          sudo wget -O /etc/yum.repos.d/jenkins.repo \
          https://pkg.jenkins.io/redhat-stable/jenkins.repo
          sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
          sudo yum upgrade
          sudo dnf install java-17-amazon-corretto -y
          sudo yum install jenkins -y
          sudo systemctl enable jenkins
          sudo systemctl start jenkins
          sudo systemctl status jenkins
          sudo cat /var/lib/jenkins/secrets/initialAdminPassword > ~/passwd.txt