AWSTemplateFormatVersion: "2010-09-09"
Description: TCS-VPC
Resources:
  TCSVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/25
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: TCS-VPC
  TCSInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: TCS-IGW
  TCSAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: TCSVPC
      InternetGatewayId:
         Ref: TCSInternetGateway
  TCSPUBSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: TCSVPC
      CidrBlock: 10.0.0.0/28
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: TCS-PUB-SUB
  TCSPUBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: TCSVPC
      CidrBlock: 10.0.0.32/28
      AvailabilityZone: "us-east-1b"
      MapPublicIpOnLaunch: "true"
      Tags:
      - Key: Name
        Value: TCS-PUB-SUB2
  TCSPVTSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: TCSVPC
      CidrBlock: 10.0.0.16/28
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: TCS-PVT-SUB
  TCSPUBRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: TCSVPC
      Tags:
      - Key: Name
        Value: TCS-PUB-RT
  TCSPVTRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: TCSVPC
      Tags:
      - Key: Name
        Value: TCS-PVT-RT
  TCSIGWRoute:
    Type: AWS::EC2::Route
    DependsOn: TCSAttachGateway
    Properties:
       RouteTableId:
         Ref: TCSPUBRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: TCSInternetGateway
  TCSPUBSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: TCSPUBSubnet
      RouteTableId:
        Ref: TCSPUBRouteTable
  TCSPUBSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: TCSPUBSubnet2
      RouteTableId:
        Ref: TCSPUBRouteTable
  TCSPVTSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: TCSPVTSubnet
      RouteTableId:
        Ref: TCSPVTRouteTable
  